# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Build Windows Release
on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        # include:
        #   - os: windows-latest
        #     vcpkgCommitId: '74e6536215718009aae747d86d84b78376bf9e09'
    steps:
   
    - uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.3'
        cache: false
   
    - name: Install dependencies
      run: |
        go get .
        .\setup_build_env.ps1
    
    - name: Build
      env:
        FOO: "BAR"
      run: |
        $env:PATH += ";D:\a\gocangateway\gocangateway\llvm-mingw\bin"
        .\build.ps1

    - name: Creating Zip
      if: startsWith(github.ref, 'refs/tags/')
      run: 7z a cangateway.zip cangateway.exe

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      env:
        GITHUB_REPOSITORY: roffe/gocangateway
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        make_latest: "true"
        files: |
          gocangateway.zip

